### ISSUE TITLE
설문요청 게시글 작성하기

### ISSUE THREAD

**Issue by eubinecto** [wisdomify/wisdomify#105]
## Why?

정의 수집 설문의 적극적 참여를 유도하는 방법을 생각해보자.

## How? 

다음의 가이드 라인을 따라야 한다.
1. 제일 중요한건 "너넨 그걸 왜하는거야?"에 대한 명확한 답을 하는 것. 즉[ Value Proposition](https://en.wikipedia.org/wiki/Value_proposition)을 피력하는 것이다. 비즈니스이건 오픈소스 프로젝트이건, 사람관계이던, 사람을 움직이는 것은 간판(e.g. 소속, 상품, 보상)이 아닌 가치(e.g. 재미있다, 돕고싶다, 나도 하고 싶다)이다. 

<img width="657" alt="image" src="https://user-images.githubusercontent.com/56193069/141642975-0d0d00c0-ce44-466e-9df1-22f6f8d73091.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/56193069/141642977-485865e8-f48e-4999-9e68-c4f801166a3b.png">
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/56193069/141642991-93ceb2c7-ca7c-4f06-968c-a9f62ed50077.png">
트위터도, 업스테이지도,  뉴럴링크도, 제일 처음으로 내세우는 것은 "우리 이만큼 돈벌고 있어요, 00학회에서 이만큼의 논문이 액셉되었어요"가 아니라, 어떤 가치를 창출하는지다. 인재들은 간판이 아닌 가치에 관심이 있기 때문에.

2. 최대한  짧고 굵고 명확한 글을 써야 한다. 사람들의 소셜 미디어에서의 attention span은 굉장히 짧다. "더보기" 버튼이 나오는 글은 쓰면 안된다. 트위터의 최대 글자 개수에 한계가 있는 것에는 이유가 있다. 짧고 굵은 글이 사람들의 이목을 끈다.
3. 깃허브 링크는 본문에 포함시킬 필요없다. 깃허브 링크는 그냥 댓글로 추가하기.

## To-do's
- [x] 설문 요청 초안 작성 by @ArtemisDicoTiar 
- [x] 설문 요청 초안 작성 by @eubinecto 
- [x] 설문 요청 초안 작성 by @teang1995 
- [x] 설문 요청 초안 작성 by @ohsuz 
- [x] 비교, 대조 및 토론을 통한 최종본 병합
- [ ] 오탈자 검사

**Comment by ArtemisDicoTiar** [comment]
@ArtemisDicoTiar 

## [카드 이미지 (pdf)](https://github.com/wisdomify/wisdomify/files/7531730/wisdomify_survey.pdf)

“ ‘어휘학습의 미래’는 ‘똑똑한 검색엔진’이다 “라는 가치를 추구하는 팀 “wisdomify”에서 여러분께 도움을 요청합니다!
“wisdomify”는 기존의 사전의 방향인 “속담” → “정의/용례”의 반대 방향으로 검색을 가능하게 하려고 합니다.
“wisdomify”에서 만들고 있는 “한글 속담 역사전”을 통해 “정의/용례” → “속담”의 검색으로 맥락과 상황에 적절한 속담을 추천받고 능동적으로 해당 속담의 학습을 돕고자 합니다.
이 “한글 속담 역사전”은 용례와 정의 데이터를 학습한 인공지능 모델을 이용해 작동합니다.

이렇게 멋져보이는 “한글 속담 역사전”이지만 현재의 성능은 형편없습니다.
적은 “속담 → 정의” 데이터만을 인공지능 모델이 학습했기 때문에 ‘특정 단어/구조에 민감하게 반응’하거나 ‘같은 의미의 단어지만 다르게 추천’하는 등의 문제가 있습니다.

이런 양질의 데이터를 “wisdomify”에게 알려주세요!

여러분이 “wisdomify”에게 속담을 풀이해주는 데이터를 이용해 기존의 문제를 해결하고 더 똑똑한 검색엔진을 만들 수 있습니다!

아래 링크를 통해 설문에 참여해주세요!
- 설문 참여 링크: https://bit.ly/3wBoLaM

설문에 참여해주신 분들에게 감사의 마음으로 상품도 준비했습니다.
(링크에 표시되는 여러 설문에 참여해 주실수록 당첨 확률이 올라갑니다

**Comment by eubinecto** [comment]
위 @ArtemisDicoTiar님의 초안에 한번 덧붙여봤습니다!
[ "Wisdomify" 오픈소스 프로젝트에서  데이터 라벨러를 모집하고 있습니다!]

Wisdomify는 문장이 주어졌을 때, 그에 적합한  용례를 추천해주는  인공지능 기반 역사전 (reverse-dictionary)입니다.  예를 들어,  첫번째 이미지처럼  홍차가 없으니 커피라도 마시자 라는 문장이 주어지면,  Wisdomify는 꿩 대신 닭 을 가장 적합한  속담으로 추천해줍니다. "어휘학습의 미래는 똑똑한 검색엔진이다"라는 가치를 바탕으로 진행중인 오픈소스 프로젝트입니다.

포부는 멋있지만, 현재 Wisdomify의 성능은 형편이 없습니다!  알파모델의 경우 겨우 50개의 데이터만을 학습했기 때문에  일반화능력이 현저히 부족합니다. 특정 단어/구조에 민감하게 반응’하거나 ‘같은 의미의 단어지만 다르게 추천’하는 등, 적어도 3개의 문제가 존재합니다.

현재로서 성능을 끌어올리는 가장 효과적인 방법은 더 많은 데이터를 확보하는 것입니다. 그래서 한국인 여러분들에게 도움을 요청드리고 싶어요.

양질의 속담 정의 데이터를 wisdomify에게 알려주세요!

여러분이 “wisdomify”에게 속담을 풀이해주는 데이터를 이용해 기존의 문제를 해결하고 더 똑똑한 검색엔진을 만들 수 있습니다!

아래 링크를 통해 설문에 참여해주세요!

설문 참여 링크: https://bit.ly/3wBoLaM
설문에 참여해주신 분들에게 감사의 마음으로 상품도 준비했습니다.
(링크에 표시되는 여러 설문에 참여해 주실수록 당첨 확률이 올라갑니다

**Comment by ArtemisDicoTiar** [comment]
카드 이미지에 
wisdomify의 현재 문제가 어떤건지는 노션에 있는 쿼리 결과 자체를 이미지로 넣는다

**Comment by eubinecto** [comment]
## 회의내용 정리
1. 이미 글에 있는 내용은 카드에 넣지 않는다. 대신 글로 설명하기 어려운 것들을 카드에 넣는다
2. 오징어게임 포스터는 제일 첫번째, 바로 이어서 1번의 내용을 붙인다.

**Comment by eubinecto** [comment]
##  최종본



## [카드 이미지 (pdf)](https://github.com/wisdomify/wisdomify/files/7531730/wisdomify_survey.pdf)

“ ‘어휘학습의 미래’는 ‘똑똑한 검색엔진’이다 “라는 가치를 추구하는 팀 “wisdomify”에서 여러분께 도움을 요청합니다!
“wisdomify”는 기존의 사전의 방향인 “속담” → “정의/용례”의 반대 방향으로 검색을 가능하게 하려고 합니다.
“wisdomify”에서 만들고 있는 “한글 속담 역사전”을 통해 “정의/용례” → “속담”의 검색으로 맥락과 상황에 적절한 속담을 추천받고 능동적으로 해당 속담의 학습을 돕고자 합니다.
이 “한글 속담 역사전”은 용례와 정의 데이터를 학습한 인공지능 모델을 이용해 작동합니다.

이렇게 멋져보이는 “한글 속담 역사전”이지만 현재의 성능은 형편없습니다.
적은 “속담 → 정의” 데이터만을 인공지능 모델이 학습했기 때문에 ‘특정 단어/구조에 민감하게 반응’하거나 ‘같은 의미의 단어지만 다르게 추천’하는 등의 문제가 있습니다.

이런 양질의 데이터를 “wisdomify”에게 알려주세요!

여러분이 “wisdomify”에게 속담을 풀이해주는 데이터를 이용해 기존의 문제를 해결하고 더 똑똑한 검색엔진을 만들 수 있습니다!

아래 링크를 통해 설문에 참여해주세요!
- 설문 참여 링크: https://bit.ly/3wBoLaM

설문에 참여해주신 분들에게 감사의 마음으로 상품도 준비했습니다.
(링크에 표시되는 여러 설문에 참여해 주실수록 당첨 확률이 올라갑니다

**Comment by teang1995** [comment]
![우리말속담](https://user-images.githubusercontent.com/23451721/141643595-dea9cf42-a393-426e-9441-e964be902e38.jpeg)

**Comment by ArtemisDicoTiar** [comment]
이후 회의는 노션에서 이어서...
