### ISSUE TITLE
Version 1  objectives

### ISSUE THREAD

**Issue by eubinecto** [wisdomify/wisdomify#19]
## To-do's
- data를 version control하는 방법에 대해서 생각해보기.
- 로깅 시스템 점검하기 - 왜 다 사라져버린걸까?
- `from_pretrained` 구현하기. 이걸 구현하면.... 코드가 깔끔해질 것 - 이걸 먼저 고려하는 것이 중요.

버전을 릴리즈 할때 마다, 가능하면 refactoring도 같이해야한다. for reproducibility.

**Comment by eubinecto** [comment]
일단 스마일게이트 멤버쉽 합격자 발표가 날때까지 기다려보자!

**Comment by eubinecto** [comment]
#26을 해결해야 이 문제를 풀수 있다.  Ainize 플랫폼에서 training을 하는 것을 해결하자.

**Comment by ArtemisDicoTiar** [comment]
## 개발
- [ ] ainize 플랫폼에서 version_0을 한번더 train 성공하기 (gpu 사용해서). @eubinecto 
- [ ] 속담 리스트는 그대로 두고,  데이터만 늘려서 version_1을 구성. @eubinecto  (시간 남는 사람이. release를 하도록 합시다.)
  - [ ] train & test: pytorch  DataModule을 사용해서, train & test loader 로 train & test  로드.  이 아이디어 참고. @teang1995  -  이슈를 하나 파서 리팩토링. 80:20을 나눠서 csv 로 저장.
- [ ]version_0를 torch_serve로??? - 해보다가, 정 안되면 플라스크로 선회. @ArtemisDicoTiar 
## 스터디
- [ ] wisdomify library -  RD 클래스 코드를  이해하기 - 노션에다가 정리.  @ArtemisDicoTiar  @teang1995  참고 자료 - 해당 논문 리뷰.

**Comment by eubinecto** [comment]
#47  이것을 끝으로  version_ 1은 어느정도 마무리가 되었다.
