### ISSUE TITLE
Version 1.2 Objectives

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [wisdomify/wisdomify#54]
# TODOs
- 모델링 (wisdomify)
  - [ ] .
- 데이터 (storyteller)
  - [x] 우리말샘 데이터 가능한 최대한으로 이번주 내 수집 완료
  - [x] 시간되면 백엔드 보일러 플레이트 코드 구출
- 프로젝트 전반 관련
  - [x] BERT 논문 리딩 마무리
  - [ ] 듀얼 임베딩 논문 (*다음주)
